version: "3"
services:
  hi_ram:
    image: shawtm/demo:latest
    deploy:
      replicas: 3
    ports:
      - "80:5000"
    networks:
      - avinash
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - avinash
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - avinash
networks:
  avinash:
